name: X16AutoShop
main: online.x16.X16AutoShop.X16AutoShop
version: 1.0-Alpha
description: A SpigotMC plugin designed to make the creation of Essentials shop signs much easier
api-version: 1.15
author: AdamW78
depend:
   - Essentials
commands:
   shopmode:
      description: Toggles automatic shop creation
      aliases: [autoshop, auto-shop, shop-mode, as, sm]
      permission: x16autoshop.toggle
      usage: "Usage: /<command> (buy/sell) [shop-size] [sign-type] [sign-color]"
      
permissions: